---
- name: Get all Red Hat Advanced Cluster Security (RHACS) RBAC Components via the ACS API
  gather_facts: false
  hosts: localhost
#  vars_prompt:
#    - name: acs_central_endpoint
#      prompt: Enter ACS Central Endpoint
#      private: no
#      confirm: no
#    - name: acs_api_token
#      prompt: Enter ACS API Token
#      private: no
#      confirm: no
  tasks:
    - name: Get Roles from ACS
      ansible.builtin.uri:
        url: "https://{{ acs_central_endpoint }}/v1/roles"
        validate_certs: no
        method: GET
        body_format: json
        status_code: [200]
        return_content: true
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ acs_api_token }}"
      register: api_return

    - name: Output Roles
      debug:
        msg: "{{ api_return.json.roles }}"

    - name: Get Permission Sets from ACS
      ansible.builtin.uri:
        url: "https://{{ acs_central_endpoint }}/v1/permissionsets"
        validate_certs: no
        method: GET
        body_format: json
        status_code: [200]
        return_content: true
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ acs_api_token }}"
      register: api_return

    - name: Output Permission Sets
      debug:
        msg: "{{ api_return.json.permissionSets }}"

    - name: Get Access Scopes from ACS
      ansible.builtin.uri:
        url: "https://{{ acs_central_endpoint }}/v1/simpleaccessscopes"
        validate_certs: no
        method: GET
        body_format: json
        status_code: [200]
        return_content: true
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ acs_api_token }}"
      register: api_return

    - name: Output Access Scopes
      debug:
        msg: "{{ api_return.json.accessScopes }}"
...
